name: 'Workflow A'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests and generate coverage report
        run: npm run test:a
      - name: Upload coverage report to Github artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-a-${{ github.run_id }}
          path: coverage-a
