name: 'Workflow C'

on:
  workflow_run:
    workflows: [Workflow A, Workflow B]
    types: [completed]

jobs:
  job-c:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch
      - name: Download coverage report from Workflow A
        uses: actions/download-artifact@v2
        with:
          name: coverage-a-${{ github.event.workflow_run.id }}
          path: coverage-a
      - name: Download coverage report from Workflow B
        uses: actions/download-artifact@v2
        with:
          name: coverage-b-${{ github.event.workflow_run.id }}
          path: coverage-b
      - name: Combine coverage reports
        run: npm run merge-coverage-reports
      - name: Upload coverage report to Github artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-c-${{ github.run_id }}
          path: coverage-c
