name: 'Workflow C'

on:
  workflow_run:
    workflows: [Workflow A, Workflow B]
    types: [completed]

jobs:
  job-c:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log out current branch name
        run: echo "Current branch name is ${{ github.head_ref }}"
