name: 'Workflow C'

on:
  workflow_run:
    workflows: [Workflow A, Workflow B]
    types: [completed]

jobs:
  job-c:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch
      - name: Install dependencies
        run: npm install
      - name: Download coverage report from Workflow A
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: workflow-a.yaml
          name: coverage-a
          path: coverage-a
      - name: Download coverage report from Workflow B
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: workflow-b.yaml
          name: coverage-b
          path: coverage-b
      - name: Combine coverage reports
        run: npm run merge-coverage-reports
      - name: Upload coverage report to Github artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-c
          path: coverage-c
