name: 'Workflow C'

on:
  workflow_run:
    workflows: [workflow-a, workflow-b]
    types:
      - completed

jobs:
  job-c:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
